<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE jmxetric-config [
   <!ELEMENT jmxetric-config (sample|ganglia|jvm)*>
   <!ELEMENT sample (mbean)*>
      <!ATTLIST sample delay CDATA #REQUIRED>
   <!ELEMENT mbean (attribute)*>
      <!ATTLIST mbean name CDATA #REQUIRED>
      <!ATTLIST mbean pname CDATA #REQUIRED>
   <!ELEMENT attribute (composite*)>
      <!ATTLIST attribute name CDATA #REQUIRED>
      <!ATTLIST attribute type CDATA "" >
      <!ATTLIST attribute units CDATA "" >
      <!ATTLIST attribute pname CDATA "" >
      <!ATTLIST attribute slope CDATA "both" >
   <!ELEMENT composite EMPTY>
      <!ATTLIST composite name CDATA #REQUIRED>
      <!ATTLIST composite type CDATA "" >
      <!ATTLIST composite units CDATA "" >
      <!ATTLIST composite pname CDATA "" >
      <!ATTLIST composite slope CDATA "both" >
   <!ELEMENT ganglia EMPTY>
      <!ATTLIST ganglia hostname CDATA #REQUIRED>
      <!ATTLIST ganglia port CDATA #REQUIRED>
      <!ATTLIST ganglia mode CDATA #REQUIRED>
      <!ATTLIST ganglia wireformat31x CDATA #REQUIRED>
   <!ELEMENT jvm EMPTY>
      <!ATTLIST jvm process CDATA "">
]>
<jmxetric-config>
  <jvm process="${groupname}" />
  <sample delay="3">
    <mbean name="java.lang:type=Memory" pname="${groupalias}.heap">
      <attribute name="HeapMemoryUsage">
        <composite name="init" pname="Heap_init" type="int32" units="bytes" />
        <composite name="committed" pname="Heap_committed" type="int32" units="bytes" />
        <composite name="used" pname="Heap_used" type="int32" units="bytes" />
        <composite name="max" pname="Heap_max" type="int32" units="bytes" />
      </attribute>
      <attribute name="NonHeapMemoryUsage">
        <composite name="init" pname="NonHeap_init" type="int32" units="bytes" />
        <composite name="committed" pname="NonHeap_committed" type="int32" units="bytes" />
        <composite name="used" pname="NonHeap_used" type="int32" units="bytes" />
        <composite name="max" pname="NonHeap_max" type="int32" units="bytes" />
      </attribute>
    </mbean>

    <mbean name="java.lang:type=MemoryPool,name=CMS Old Gen" pname="${groupalias}.cmsoldgen">
      <attribute name="Usage" type="int32" units="bytes" />
    </mbean>


    <mbean name="java.lang:type=GarbageCollector,name=ConcurrentMarkSweep" pname="${groupalias}.gc">
      <attribute name="CollectionCount" type="int32" units="bytes" />
      <attribute name="CollectionTime" type="int32" units="bytes" />
    </mbean>
    
    <mbean name="java.lang:type=GarbageCollector,name=ParNew" pname="${groupalias}.gc">
      <attribute name="CollectionCount" type="int32" units="bytes" />
      <attribute name="CollectionTime" type="int32" units="bytes" />
    </mbean>

    <mbean name="java.lang:type=Threading" pname="${groupalias}.threads">
      <attribute name="DaemonThreadCount" type="int16" />
      <attribute name="PeakThreadCount" type="int16" />
      <attribute name="ThreadCount" type="int16" />
      <attribute name="TotalStartedThreadCount" type="int16" />
    </mbean>

    <mbean name="java.lang:type=OperatingSystem" pname="${groupalias}.OS">
      <attribute name="ProcessCpuTime" type="int32" slope="positive" />
    </mbean>
        
    <mbean name="solr/${solrcore}:type=/select,id=org.apache.solr.handler.component.SearchHandler" pname="${groupalias}.select">
      <attribute name="requests" type="int32"/>
      <attribute name="errors" type="int32"/>
      <attribute name="timeouts" type="int32"/>
      <attribute name="totalTime" type="double"/>
      <attribute name="avgRequestsPerSecond" type="double"/>
      <attribute name="avgTimePerRequest" type="double"/>
      <attribute name="medianRequestTime" type="double"/>
      <attribute name="5minRateReqsPerSecond" type="double"/>
      <attribute name="15minRateReqsPerSecond" type="double"/>
      <attribute name="75thPcRequestTime" type="double"/>
      <attribute name="95thPcRequestTime" type="double"/>
      <attribute name="99thPcRequestTime" type="double"/>
      <attribute name="999thPcRequestTime" type="double"/>
    </mbean>    
  </sample>
  <ganglia hostname="localhost" port="8649" mode="multicast" wireformat31x="true" />
</jmxetric-config>

